---
settings:
  name: Global File Cache
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: de-de,us-en,ja-jp,zh-cn,zh-tw,ko-kr,fr-fr
sidebar:
  entries:
  - title: Dokumente zum Global File Cache
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Probleme wurden behoben
      url: "/fixed-issues.html"
  - title: Los geht's
    entries:
    - title: Erfahren Sie mehr über Global File Cache
      url: "/concept-gfc.html"
    - title: Voraussetzungen für den globalen Datei-Cache
      url: "/concept-before-you-begin-to-deploy-gfc.html"
    - title: Bereitstellung und Lizenzierung von Global File Cache
      url: "/task-gfc-getting-started.html"
    - title: Voraussetzungen für Global File Cache Edge
      url: "/download-gfc-resources.html"
    - title: Implementierung Von Global File Cache Edge
      url: "/task-deploy-gfc-edge-instances.html"
  - title: Global File Cache Verwenden
    entries:
    - title: Endbenutzerschulung
      url: "/concept-gfc-enduser-training.html"
    - title: Weitere Informationen
      url: "/reference-gfc-additional-information.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Erfahren Sie mehr über Global File Cache
      url: concept-gfc.html
    - title: Was ist neu
      url: whats-new.html
    - title: Einschränkungen
      url: concept-gfc.html#limitations
  - title: Implementierung von Komponenten
    links:
    - title: Implementieren Sie Cloud Volumes ONTAP als Storage-Plattform
      url: task-gfc-getting-started.html#deploy-cloud-volumes-ontap-as-your-storage-platform
    - title: Bereitstellung von Global File Cache Management Server und Global File
        Cache Core
      url: task-gfc-getting-started.html#enable-global-file-cache-in-your-working-environment
    - title: Implementierung globaler File Cache Edge-Instanzen
      url: task-deploy-gfc-edge-instances.html
  - title: Benutzer Schulen
    links:
    - title: Endbenutzerschulung
      url: concept-gfc-enduser-training.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: BlueXP-Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
  - title: Andere Ressourcen
    links:
    - title: Anwendungsfälle für BlueXP
      url: https://cloud.netapp.com/global-file-cache
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle BlueXP-Dokumentationen
